### ISSUE TITLE
Add a product

### ISSUE THREAD

**Issue by harshit1142** [harshit1142/e-commerce#1]
Add more project details in src/data/products.json

Do star 🌟 the repo and directly make a PR.

**Comment by Jash2606** [comment]
Hey @harshit1142 ,
I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

**Comment by harshit1142** [comment]
@Jash2606 Done.

**Comment by HackesticMedusa** [comment]
Hey @harshit1142 ,
I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

**Comment by harshit1142** [comment]
@HackesticMedusa Yes, you can add new products too. Do star ⭐ the repo.

**Comment by HackesticMedusa** [comment]
> @HackesticMedusa Yes, you can add new products too. Do star ⭐ the repo.

Can I also update the README.md? Also Add a CONTRIBUTING.md file with contribution guidelines to your repository.

**Comment by harshit1142** [comment]
@HackesticMedusa why not, request it in the respective issue or create a new issue(if there is no such issue) .There I will assign the task.

**Comment by HackesticMedusa** [comment]
Can you add a CONTRIBUTING.md file with contribution guidelines to your repository?

**Comment by anirudh-why** [comment]
please assign this issue to me under hactober fest

**Comment by harshit1142** [comment]
@anirudh-why Sure.

**Comment by Utsav631** [comment]
Could you please assign this to me under hoctoberfest, I wanna work on this issue.

**Comment by harshit1142** [comment]
@Utsav631 You can make a PR.

**Comment by Pariyul** [comment]
Hey I want to Contribute in this Can you please assign it to me.

**Comment by harshit1142** [comment]
@Pariyul you can make a PR.

**Comment by Samyak137** [comment]
I already made a PR will you go through it.

**Comment by Arpit529Srivastava** [comment]
@harshit1142 can you please assign the issue to me. I can work on it

**Comment by harshit1142** [comment]
@Arpit529Srivastava make a PR.

**Comment by Arpit529Srivastava** [comment]
@harshit1142 i am thinking of add a new page for sign in where people can login or sign up for the website

**Comment by Pariyul** [comment]
Hey, I already made a PR will you go through it.

**Comment by biswajit-sarkar-007** [comment]
Hi, I'm interested in solving this. Can I be assigned?

**Comment by harshit1142** [comment]
@biswajit-sarkar-007 Make a PR.

**Comment by biswajit-sarkar-007** [comment]
@harshit1142, I have already completed this PR for issue #52.

**Comment by harshit1142** [comment]
@biswajit-sarkar-007  yeah, it's merged

**Comment by Arpit529Srivastava** [comment]
@harshit1142 i would like to work on this issue under ```Hacktoberfest```

**Comment by harshit1142** [comment]
@Arpit529Srivastava Make a PR.

**Comment by Ankesh2004** [comment]
@harshit1142  i would like to work on this issue under Hacktoberfest

**Comment by harshit1142** [comment]
@Ankesh2004 Make a PR

**Comment by Ankesh2004** [comment]
@harshit1142 I have raised a [PR](https://github.com/harshit1142/e-commerce/pull/99) check it
