### ISSUE TITLE
react-icons dependency used in Navbar.js but not updated in package.json

### ISSUE THREAD

**Issue by itSarthak** [harshit1142/e-commerce#21]
Someone updated Navbar.js file 2 days ago but package.json file was last edited 7 months ago, which means it is not updated properly. Due to which the application is not working when `npm start` command is used. Please ask for more info if I am not clear enough.

**Comment by harshit1142** [comment]
@itSarthak Fix it. Do star ⭐the repo and follow me to start.

**Comment by itSarthak** [comment]
When I try to run this project locally, that is after following the below steps
1. Fork the repo
2. `git clone` locally
3. npm install
4. npm run

The following error is displayed
![image](https://github.com/user-attachments/assets/18cff8eb-7468-4d0f-9d64-4184f97331e7)

which can be easily explained since there is no react-icons dependency mentioned in packed.json file 
![image](https://github.com/user-attachments/assets/b8797496-35eb-491c-909e-7d9c20988cb2)

But it is clearly used in the navbar.js fle on line 7
![image](https://github.com/user-attachments/assets/7476f239-a336-470b-ab3c-30665ce4d182)

This is breaking the local build, and it can be easily fixed by simply adding `"react-icons": "^5.3.0"` in package.json file.

**Comment by harshit1142** [comment]
@itSarthak Great !! You can work on it.

**Comment by itSarthak** [comment]
Thanks for merging the pr
