### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by Prathamesh0901** [harshit1142/e-commerce#24]
![image](https://github.com/user-attachments/assets/344ccaec-e16b-4dd4-a13a-845c20e00b7e)
on the published site, the description of the product is not consistent neither visible completely.

I would love to make changes in the ui regarding this.

**Comment by harshit1142** [comment]
@Prathamesh0901 It got changed. Please Fix UI.

Do star ⭐ the repo and follow me to start.

**Comment by Prathamesh0901** [comment]
![image](https://github.com/user-attachments/assets/fa492130-8a34-424e-8739-2f3908cec58e)
is this ok? @harshit1142

**Comment by harshit1142** [comment]
@Prathamesh0901 yeah fine. Do up-to-date your branch with my main branch before making PR.

**Comment by harshit1142** [comment]
Fixed
