### ISSUE TITLE
Make the UI more responsive

### ISSUE THREAD

**Issue by Aiu26** [harshit1142/e-commerce#25]
- can add hover effect to the cards
- add style to the page

**Comment by Aiu26** [comment]
under hackotberfest

**Comment by harshit1142** [comment]
@Aiu26 I will assign you after a few UI pull requests.

**Comment by Aiu26** [comment]
ok sure

**Comment by harshit1142** [comment]
@Aiu26 take the latest commit. Assigned.

Star ⭐ the repo .
