### ISSUE TITLE
Add Search Functionality For Products

### ISSUE THREAD

**Issue by its-kumar-yash** [harshit1142/e-commerce#27]
I will implement search functionality among products, as right now search bar does not work

**Comment by harshit1142** [comment]
@its-kumar-yash Go head.

Do star ⭐ the repo.

**Comment by its-kumar-yash** [comment]
> git remote rename upstream upstream
error: remote upstream already exists.

getting error while pushing code

**Comment by harshit1142** [comment]
@its-kumar-yash git push --set-upstream origin branchName

**Comment by its-kumar-yash** [comment]
Thanks

**Comment by Pariyul** [comment]
Hey , I have to work on that will you please assign it to me.

**Comment by harshit1142** [comment]
@Pariyul Someone is already working on it.

**Comment by its-kumar-yash** [comment]
@harshit1142  Check now
