### ISSUE TITLE
Improve Navbar Design

### ISSUE THREAD

**Issue by harshit1142** [harshit1142/e-commerce#3]

**Comment by Jash2606** [comment]
Hey @harshit1142 ,
I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me?

**Comment by harshit1142** [comment]
@Jash2606 Yes, you can work on the issue. Star  ⭐ the repo and follow me to start.

**Comment by anirudh-why** [comment]
intrested to work on this issue

**Comment by harshit1142** [comment]
@anirudh-why Someone already assigned to navbar . You can go through the website to improve other components ( [harshit-ecommerce.netlify.app/](https://harshit-ecommerce.netlify.app/) ) . Create a new issue if find.
