### ISSUE TITLE
The better card component.

### ISSUE THREAD

**Issue by Utsav631** [harshit1142/e-commerce#32]
I wanna contribute to this by bettering the card component UI.
![{1E6DA08E-0F6A-422A-89EF-610CD08C2CDD}](https://github.com/user-attachments/assets/e86bb813-5cd2-462d-b728-0e9fda15a029)

**Comment by harshit1142** [comment]
@Utsav631 Sure.
Do star 🌟 the repo.

**Comment by Pariyul** [comment]
I have to work on that will you please assign it to me.

**Comment by harshit1142** [comment]
@Pariyul it is already assigned.

**Comment by harshit1142** [comment]
Fixed.
