### ISSUE TITLE
Image not loading for Xiaomi 14 CIVI.

### ISSUE THREAD

**Issue by dead-shadow-7** [harshit1142/e-commerce#35]
![Screenshot 2024-10-04 123159](https://github.com/user-attachments/assets/81f5c706-d7a3-4801-90d4-3a1b7cf3feae)

**Comment by dead-shadow-7** [comment]
Can I work on this issue?

**Comment by harshit1142** [comment]
@dead-shadow-7 Star 🌟 the repo and good to go.
