### ISSUE TITLE
Update Readme.md file

### ISSUE THREAD

**Issue by harshit1142** [harshit1142/e-commerce#4]
Add relevant information in the readme.md

**Comment by HackesticMedusa** [comment]
Hey @harshit1142 ,
I'd like to contribute to this issue for Hacktoberfest . Could you please assign it to me? I also sent you a connection request in LinkedIn

**Comment by harshit1142** [comment]
@HackesticMedusa Done. Great to be connected!!

**Comment by hemanthhhhhh** [comment]
Would like to contribute .Assign please

**Comment by harshit1142** [comment]
@hemanthhhhhh add this code at the last of readme.md file 


## Contributors 

`<p align="center"><a href="https://github.com/harshit1142/e-commerce/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=harshit1142/e-commerce" max={1000} columns={100} anon={1}/>
</a></p>`
