### ISSUE TITLE
Styling of cards on home page needs to  improve

### ISSUE THREAD

**Issue by Aaditya8C** [harshit1142/e-commerce#42]
https://github.com/user-attachments/assets/410bc5e5-a310-47e5-a583-d88ad66daab2

I'll improve the design and color combination of cards which will be aligned with the website properly

**Comment by harshit1142** [comment]
@Aaditya8C done. Star ⭐ the repo and follow me to start.

**Comment by Pariyul** [comment]
Hey I want to contribute in this I can make card flip backside. Kindly Assign me this under hacktoberfest2024

**Comment by harshit1142** [comment]
@Pariyul let you know.

**Comment by Aaditya8C** [comment]
Hey @Pariyul I've raised the PR regarding the changes. Check it once.
