### ISSUE TITLE
BUG : Navbar Text is Too Dark

### ISSUE THREAD

**Issue by its-kumar-yash** [harshit1142/e-commerce#45]
this text should be in white color as current text is not visible

![image](https://github.com/user-attachments/assets/a484274a-3279-468b-8c51-8a24a9f02002)

**Comment by harshit1142** [comment]
@its-kumar-yash Do star 🌟 the repo and follow me to start.

**Comment by harshit1142** [comment]
@its-kumar-yash Fixed
