### ISSUE TITLE
bug report: clicking on add to wishlist button does not do so

### ISSUE THREAD

**Issue by Prathamesh0901** [harshit1142/e-commerce#59]
![image](https://github.com/user-attachments/assets/ba5b4b16-640d-4879-8bd0-070d2b812650)
instead of adding the product to the wishlist instead it just shows the information of the product(same as what the More Info button does)

I would love to work on this issue.

**Comment by harshit1142** [comment]
@Prathamesh0901 Sure.

**Comment by Prathamesh0901** [comment]
![image](https://github.com/user-attachments/assets/c1ef0321-e374-4c00-b37a-edf103e8633e)
we need to show the wishlist products on separate page, right?
if yes which route should i use for that?

**Comment by harshit1142** [comment]
@Prathamesh0901 /wishlist . Feel free to modify
