### ISSUE TITLE
Fixed Description Length for Product Listing Cards and align buttons

### ISSUE THREAD

**Issue by AnandRP2030** [harshit1142/e-commerce#62]
On the product listing page, the descriptions for each product vary in length, causing inconsistencies in the layout of the product cards. Specifically, the "More Info" and "Add to Wishlist" buttons are misaligned because the description text takes up different amounts of space (ranging from 2 to 4 lines or more). This issue affects the visual appeal and user experience of the product listing page.

To address this issue, I suggest implementing a uniform height for the description area within each product card. If the description length exceeds this height, we can add an ellipsis ("...") to indicate that there are more details available. 
![Screenshot 2024-10-08 173107](https://github.com/user-attachments/assets/a2d7db1a-bd71-4e35-a74e-88e47351e591)
![product-cards](https://github.com/user-attachments/assets/d1886e1c-c9ea-4133-94dd-85991512b250)

**Comment by AnandRP2030** [comment]
@harshit1142 i can fix this issue, can you assign this to me under Hacktoberfest event.

**Comment by harshit1142** [comment]
@AnandRP2030 Do star 🌟 the repo and follow me to start.

**Comment by harshit1142** [comment]
Fixed
