### ISSUE TITLE
BUG: Re-Enter password updates password

### ISSUE THREAD

**Issue by harshbhar0629** [harshit1142/e-commerce#69]
When we try to re-enter the password then whatever password we have write in password input it erase and it change onChanging of re-enter password.

**Behaviour:**

https://github.com/user-attachments/assets/3d1fa5b2-721a-42c3-b105-1fa09ca34327

@harshit1142  Please assign to me this issue under gssoc-ext, hacktoberfest-accepted.

**Comment by harshit1142** [comment]
@harshbhar0629 you can fix it.
