### ISSUE TITLE
BUG: Signup-btn Not working

### ISSUE THREAD

**Issue by harshbhar0629** [harshit1142/e-commerce#71]
When we click on signup btn then it will not doing anything now but if when we click on signup btn then it give one notification with successfully-signup and also redirect to home page it will increase user interaction toward website.

**Behaviour:**

https://github.com/user-attachments/assets/afd50ca8-ab5f-4cb2-a531-2200b980acb7

@harshit1142 Please assign this issue to me under gssoc-ext, hacktoberfest-accepted with level-2.

**Comment by harshit1142** [comment]
@harshbhar0629 Sure.Do star ✨ the repo .

**Comment by harshbhar0629** [comment]
Ok, Done
