### ISSUE TITLE
BUG: Cards overlaps

### ISSUE THREAD

**Issue by harshbhar0629** [harshit1142/e-commerce#80]
When we hover to home page cards then it overlaps to each other.

https://github.com/user-attachments/assets/9df242ff-6e38-481a-b180-3438d53702de

@harshit1142 Please assign to me this issue under **gssoc-ext, hacktoberfest-accepted, level-2** with all three labels.

**Comment by harshit1142** [comment]
@harshbhar0629 that's not a point to concern
