### ISSUE TITLE
[Bug]:Minor bug in WishList.js

### ISSUE THREAD

**Issue by parvkumra** [harshit1142/e-commerce#83]
There is a bug in WishList.js at line number 8
<img width="1440" alt="Screenshot 2024-10-13 at 6 57 42 PM" src="https://github.com/user-attachments/assets/9279c982-5346-4399-99e2-b39f5a10aa7b">
please assign this minor issue to me ,i want to update this and the card ui on the home page

**Comment by parvkumra** [comment]
i have fixed the bug in Wishlist.js , can you once review the ui before i make the pull request
<img width="1440" alt="Screenshot 2024-10-13 at 8 38 07 PM" src="https://github.com/user-attachments/assets/77860cb3-26eb-48b6-a2ba-1cd289de7063">
keeping in mind the color of theme of the site ,and aligned the card components in centre

**Comment by harshit1142** [comment]
@parvkumra make a PR
