### ISSUE TITLE
Feat: Add Backend Functionality to the Website

### ISSUE THREAD

**Issue by suryapratap04** [harshit1142/e-commerce#85]
We need to integrate backend functionality into our  website to enhance its performance and provide essential features. This will involve setting up a server-side framework, implementing API endpoints, and connecting to a database for product management, user authentication, and order processing.

@harshit1142 assign this issue to me with hacktoberfest and hacktoberfest-accepted tag

**Comment by suryapratap04** [comment]
please assign me with gssoc-ext, level-3. tags

**Comment by harshit1142** [comment]
@suryapratap04 it is a pure front-end website
