### ISSUE TITLE
BUG: No Error handling for 404 page

### ISSUE THREAD

**Issue by harshbhar0629** [harshit1142/e-commerce#88]
In your website there is no error handling if someone is try to access path which is not exist then by default browser show its 404page not found but you can manually handle 404 page.

@harshit1142 Please assign to me this issue under **gssoc-ext, hacktoberfest-accepted, level-2**

**Comment by harshbhar0629** [comment]
@harshit1142  Please apply the labels **gssoc-ext, hactoberfest-accepted**.

**Comment by harshbhar0629** [comment]
@harshit1142   Is this repo taking part in girl summer script of code 2024??

**Comment by harshit1142** [comment]
No, only Hacktoberfest
