### ISSUE TITLE
UI Improvement: Navbar Design, Sign-in/Logout Button, and Search Input/Responsiveness

### ISSUE THREAD

**Issue by VedantDewangan** [harshit1142/e-commerce#9]
Hey @harshit1142,
I noticed that the current navbar could benefit from some UI improvements. The sign-in and logout buttons are not well positioned, and the search input and button lack proper styling. Additionally, the navbar doesn't look good on responsive screens, and I believe enhancing it could greatly improve the user experience.

As part of Hacktoberfest, I would love to work on this and give the navbar a cleaner, more professional look. I’ll ensure that the buttons are properly aligned, the search input is better styled, and the responsiveness is significantly improved. Please assign this issue to me, and I promise to deliver a better UI. Thank you!

Looking forward to contributing!

**Comment by harshit1142** [comment]
@VedantDewangan Look good, you can work on the issue
