### ISSUE TITLE
[BUG]: Error while running locally

### ISSUE THREAD

**Issue by suryapratap04** [harshit1142/e-commerce#92]
After setting up the project locally there are some errors occur 

![Screenshot from 2024-10-17 00-05-21](https://github.com/user-attachments/assets/b7abb25c-8b16-4b29-97ec-b5f6c0f8f954)

![image](https://github.com/user-attachments/assets/2f09253f-8386-4e96-ac54-b0e3369e4853)

**Comment by arbazahmed07** [comment]
hey @suryapratap04 
can you assign me this
